/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./js/**/*.{js,ts}",
    "./css/**/*.css"
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb5",
        "inverse-primary": "#613ede",
        "on-error": "#690005",
        "on-tertiary": "#452b00",
        "outline": "#938ea1",
        "on-secondary": "#00382a",
        "tertiary-container": "#c58311",
        "surface-container-highest": "#33343d",
        "border-glass": "rgba(255, 255, 255, 0.12)",
        "surface-variant": "#33343d",
        "primary": "#cabeff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#481bc6",
        "surface-container": "#1d1f28",
        "soft-coral": "#F06A8E",
        "on-tertiary-container": "#3d2500",
        "mesh-glow-amber": "rgba(242, 169, 59, 0.18)",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#633f00",
        "primary-fixed": "#e6deff",
        "surface-tint": "#cabeff",
        "surface-glass": "rgba(20, 24, 38, 0.65)",
        "error": "#ffb4ab",
        "on-surface": "#e2e1ed",
        "surface": "#11131b",
        "secondary": "#3edeb2",
        "surface-bright": "#373942",
        "background": "#11131b",
        "surface-dim": "#11131b",
        "on-primary-fixed": "#1c0062",
        "on-tertiary-fixed": "#2a1800",
        "on-primary": "#32009a",
        "secondary-container": "#00c297",
        "outline-variant": "#484555",
        "secondary-fixed": "#63fbcd",
        "primary-container": "#947dff",
        "surface-container-low": "#191b24",
        "surface-container-lowest": "#0c0e16",
        "on-primary-container": "#2b0088",
        "inverse-on-surface": "#2e3039",
        "secondary-fixed-dim": "#3edeb2",
        "surface-container-high": "#282a32",
        "mesh-glow-indigo": "rgba(124, 93, 250, 0.28)",
        "tertiary": "#ffb956",
        "on-secondary-fixed": "#002117",
        "mesh-glow-coral": "rgba(240, 106, 142, 0.2)",
        "border-glass-highlight": "rgba(255, 255, 255, 0.24)",
        "inverse-surface": "#e2e1ed",
        "mesh-glow-emerald": "rgba(45, 212, 168, 0.22)",
        "on-surface-variant": "#c9c4d7",
        "on-secondary-container": "#004937",
        "primary-fixed-dim": "#cabeff",
        "on-secondary-fixed-variant": "#00513e",
        "tertiary-fixed-dim": "#ffb956",
        "on-background": "#e2e1ed",
        "surface-glass-active": "rgba(30, 36, 56, 0.8)"
      },
      spacing: {
        "space-2xl": "3rem",
        "gutter-desktop": "1.5rem",
        "space-4xl": "6rem",
        "margin-mobile": "1.25rem",
        "space-xl": "2rem",
        "space-3xs": "0.125rem",
        "space-sm": "0.75rem",
        "margin-desktop": "3rem",
        "space-3xl": "4rem",
        "space-2xs": "0.25rem",
        "space-md": "1rem",
        "space-xs": "0.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-xl": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "phonetic-ipa": ["Inter", "sans-serif"],
        "headline-display-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-xl": ["18px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }],
        "headline-display": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "phonetic-ipa": ["15px", { "lineHeight": "22px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "headline-display-mobile": ["38px", { "lineHeight": "46px", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "700" }]
      }
    }
  },
  plugins: []
};
